### ISSUE TITLE
Starting the development server fails if port is in use

### ISSUE THREAD

**Issue by vsaarinen** [lucified/lucify-component-builder#21]
Running `gulp` when port 3000 is in use results in the following error message:

```
[19:29:51] Starting 'bundle-components'...
[19:29:51] 'bundle-components' errored after 37 ms
[19:29:51] Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)
[19:29:51] 'build' errored after 10 s
[19:29:51] Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)
[19:29:51] 'default' errored after 10 s
[19:29:51] Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)
```

**Comment by juhoojala** [comment]
Fixed by https://github.com/lucified/lucify-component-builder/pull/22
